import { useMemo, useState } from 'react';
import { ClipboardList, RefreshCw } from 'lucide-react';
import StatCard from '../components/StatCard.jsx';
import TaskToolbar from '../components/TaskToolbar.jsx';
import TaskCard from '../components/TaskCard.jsx';
import Modal from '../components/Modal.jsx';
import TaskForm from '../components/TaskForm.jsx';

export default function Dashboard({ tasks, loading, error, onRetry, onCreate, onUpdate, onDelete, onComplete }) {
 const [query,setQuery]=useState(''),[status,setStatus]=useState('All'),[priority,setPriority]=useState('All'),[sort,setSort]=useState('newest');
 const filtered=useMemo(()=>tasks.filter(t=>{const q=query.toLowerCase(); return (!q||`${t.title} ${t.description}`.toLowerCase().includes(q))&&(status==='All'||t.status===status)&&(priority==='All'||t.priority===priority)}).sort((a,b)=>{if(sort==='title') return a.title.localeCompare(b.title); if(sort==='priority') return ({High:0,Medium:1,Low:2}[a.priority]-({High:0,Medium:1,Low:2}[b.priority])); if(sort==='dueSoon') return (a.dueDate?new Date(a.dueDate):new Date('2999'))-(b.dueDate?new Date(b.dueDate):new Date('2999')); return new Date(b.createdAt)-new Date(a.createdAt)}),[tasks,query,status,priority,sort]);
 const stats={total:tasks.length,todo:tasks.filter(t=>t.status==='Todo').length,progress:tasks.filter(t=>t.status==='In Progress').length,completed:tasks.filter(t=>t.status==='Completed').length};
 return <><section className="mb-7 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-indigo-600">Good to see you</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-900 dark:text-white">Dashboard</h1><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Plan the work. Track the progress. Ship it.</p></div><button onClick={onRetry} className="btn-secondary w-fit"><RefreshCw size={16}/> Refresh</button></section><div className="mb-7 grid grid-cols-2 gap-4 xl:grid-cols-4"><StatCard type="total" label="Total tasks" value={stats.total}/><StatCard type="todo" label="Todo" value={stats.todo}/><StatCard type="progress" label="In progress" value={stats.progress}/><StatCard type="completed" label="Completed" value={stats.completed}/></div><TaskToolbar {...{query,setQuery,status,setStatus,priority,setPriority,sort,setSort}} onCreate={onCreate}/><section className="mt-6"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-bold text-slate-900 dark:text-white">Recent tasks</h2><p className="text-sm text-slate-500 dark:text-slate-400">{filtered.length} task{filtered.length!==1?'s':''} matching your view</p></div></div>{loading?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(i=><div key={i} className="card h-48 animate-pulse bg-slate-100 dark:bg-slate-800"/>)}</div>:error?<div className="card py-14 text-center"><p className="font-bold text-rose-500">Could not load tasks</p><p className="mt-1 text-sm text-slate-500">{error}</p><button onClick={onRetry} className="btn-primary mt-4">Try again</button></div>:filtered.length===0?<div className="card py-16 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-indigo-50 text-indigo-600 dark:bg-indigo-500/10"><ClipboardList/></div><h3 className="mt-4 font-bold text-slate-900 dark:text-white">No tasks found</h3><p className="mt-1 text-sm text-slate-500">Create a task or adjust your filters.</p></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(t=><TaskCard key={t._id} task={t} onEdit={onUpdate} onDelete={onDelete} onComplete={onComplete}/>)}</div>}</section></>;
}
